// <auto-generated />
using System;
using Lending_CapstoneProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lending_CapstoneProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919055147_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanApplication", b =>
                {
                    b.Property<int>("LoanApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanApplicationId"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanOfficerId")
                        .HasColumnType("int");

                    b.Property<int>("LoanSchemeId")
                        .HasColumnType("int");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RepaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LoanApplicationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanOfficerId");

                    b.HasIndex("LoanSchemeId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanBank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BankId");

                    b.ToTable("LoanBanks");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanBranch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.HasIndex("BankId");

                    b.ToTable("LoanBranches");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanScheme", b =>
                {
                    b.Property<int>("LoanSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanSchemeId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinCreditScore")
                        .HasColumnType("int");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LoanSchemeId");

                    b.HasIndex("BankId");

                    b.ToTable("LoanSchemes");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.Repayment", b =>
                {
                    b.Property<int>("RepaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RepaymentId");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("Repayments");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoanBankId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("LoanBankId");

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("UserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.Customer", b =>
                {
                    b.HasBaseType("Lending_CapstoneProject.Models.User");

                    b.Property<string>("AadharId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PanId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasIndex("BranchId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("BranchId")
                                .HasColumnName("Customer_BranchId");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanAdmin", b =>
                {
                    b.HasBaseType("Lending_CapstoneProject.Models.User");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanOfficer", b =>
                {
                    b.HasBaseType("Lending_CapstoneProject.Models.User");

                    b.Property<string>("AssignedCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LoanBankBankId")
                        .HasColumnType("int");

                    b.HasIndex("BranchId");

                    b.HasIndex("LoanBankBankId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.SystemAdministrator", b =>
                {
                    b.HasBaseType("Lending_CapstoneProject.Models.User");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanApplication", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.Customer", "Customer")
                        .WithMany("LoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lending_CapstoneProject.Models.LoanOfficer", "LoanOfficer")
                        .WithMany("AssignedApplications")
                        .HasForeignKey("LoanOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lending_CapstoneProject.Models.LoanScheme", "LoanScheme")
                        .WithMany()
                        .HasForeignKey("LoanSchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanOfficer");

                    b.Navigation("LoanScheme");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanBranch", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.LoanBank", "LoanBank")
                        .WithMany("LoanBranches")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanBank");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanScheme", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.LoanBank", "LoanBank")
                        .WithMany("LoanSchemes")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanBank");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.Repayment", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.LoanApplication", "LoanApplication")
                        .WithMany("Repayments")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.User", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.LoanBank", "LoanBank")
                        .WithMany("Users")
                        .HasForeignKey("LoanBankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoanBank");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.Customer", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.LoanBranch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanOfficer", b =>
                {
                    b.HasOne("Lending_CapstoneProject.Models.LoanBranch", "Branch")
                        .WithMany("Officers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lending_CapstoneProject.Models.LoanBank", null)
                        .WithMany("LoanOfficers")
                        .HasForeignKey("LoanBankBankId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanApplication", b =>
                {
                    b.Navigation("Repayments");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanBank", b =>
                {
                    b.Navigation("LoanBranches");

                    b.Navigation("LoanOfficers");

                    b.Navigation("LoanSchemes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanBranch", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Officers");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.Customer", b =>
                {
                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("Lending_CapstoneProject.Models.LoanOfficer", b =>
                {
                    b.Navigation("AssignedApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
